// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: jobqueue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClaimJobRequest is sent by a worker to claim the next available job.
type ClaimJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`              // unique ID of the requesting worker
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`           // which queue to pull from ("default" if empty)
	LeaseSeconds  int32                  `protobuf:"varint,3,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"` // requested lease duration in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimJobRequest) Reset() {
	*x = ClaimJobRequest{}
	mi := &file_jobqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobRequest) ProtoMessage() {}

func (x *ClaimJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobRequest.ProtoReflect.Descriptor instead.
func (*ClaimJobRequest) Descriptor() ([]byte, []int) {
	return file_jobqueue_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ClaimJobRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *ClaimJobRequest) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

// ClaimJobResponse is returned when a job is successfully claimed.
// If no jobs are available, the RPC returns a NOT_FOUND status code
// rather than a populated response — workers check the gRPC status, not this message.
type ClaimJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskName      string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // raw JSON bytes — worker parses based on task_name
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	RetryCount    int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimJobResponse) Reset() {
	*x = ClaimJobResponse{}
	mi := &file_jobqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobResponse) ProtoMessage() {}

func (x *ClaimJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobResponse.ProtoReflect.Descriptor instead.
func (*ClaimJobResponse) Descriptor() ([]byte, []int) {
	return file_jobqueue_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ClaimJobResponse) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ClaimJobResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClaimJobResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ClaimJobResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ClaimJobResponse) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

// CompleteJobRequest marks a job as successfully finished.
type CompleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // must match the worker that claimed the job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_jobqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_jobqueue_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// FailJobRequest marks a job as permanently failed or schedules a retry.
type FailJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Permanent     bool                   `protobuf:"varint,4,opt,name=permanent,proto3" json:"permanent,omitempty"`                     // if true, go straight to dead letter (no retry)
	RetryCount    int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"` // current retry count from ClaimJobResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailJobRequest) Reset() {
	*x = FailJobRequest{}
	mi := &file_jobqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailJobRequest) ProtoMessage() {}

func (x *FailJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailJobRequest.ProtoReflect.Descriptor instead.
func (*FailJobRequest) Descriptor() ([]byte, []int) {
	return file_jobqueue_proto_rawDescGZIP(), []int{3}
}

func (x *FailJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FailJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FailJobRequest) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *FailJobRequest) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

func (x *FailJobRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// Empty response — used when the caller only needs to know if the RPC succeeded.
type JobAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAck) Reset() {
	*x = JobAck{}
	mi := &file_jobqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAck) ProtoMessage() {}

func (x *JobAck) ProtoReflect() protoreflect.Message {
	mi := &file_jobqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAck.ProtoReflect.Descriptor instead.
func (*JobAck) Descriptor() ([]byte, []int) {
	return file_jobqueue_proto_rawDescGZIP(), []int{4}
}

func (x *JobAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_jobqueue_proto protoreflect.FileDescriptor

const file_jobqueue_proto_rawDesc = "" +
	"\n" +
	"\x0ejobqueue.proto\x12\bjobqueue\"r\n" +
	"\x0fClaimJobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12#\n" +
	"\rlease_seconds\x18\x03 \x01(\x05R\fleaseSeconds\"\xbe\x01\n" +
	"\x10ClaimJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\"H\n" +
	"\x12CompleteJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"\xa0\x01\n" +
	"\x0eFailJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12\x1c\n" +
	"\tpermanent\x18\x04 \x01(\bR\tpermanent\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\"\x1f\n" +
	"\x06JobAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2\xca\x01\n" +
	"\x0fJobQueueService\x12A\n" +
	"\bClaimJob\x12\x19.jobqueue.ClaimJobRequest\x1a\x1a.jobqueue.ClaimJobResponse\x12=\n" +
	"\vCompleteJob\x12\x1c.jobqueue.CompleteJobRequest\x1a\x10.jobqueue.JobAck\x125\n" +
	"\aFailJob\x12\x18.jobqueue.FailJobRequest\x1a\x10.jobqueue.JobAckB3Z1github.com/distributed-job-queue/internal/grpc/pbb\x06proto3"

var (
	file_jobqueue_proto_rawDescOnce sync.Once
	file_jobqueue_proto_rawDescData []byte
)

func file_jobqueue_proto_rawDescGZIP() []byte {
	file_jobqueue_proto_rawDescOnce.Do(func() {
		file_jobqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobqueue_proto_rawDesc), len(file_jobqueue_proto_rawDesc)))
	})
	return file_jobqueue_proto_rawDescData
}

var file_jobqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jobqueue_proto_goTypes = []any{
	(*ClaimJobRequest)(nil),    // 0: jobqueue.ClaimJobRequest
	(*ClaimJobResponse)(nil),   // 1: jobqueue.ClaimJobResponse
	(*CompleteJobRequest)(nil), // 2: jobqueue.CompleteJobRequest
	(*FailJobRequest)(nil),     // 3: jobqueue.FailJobRequest
	(*JobAck)(nil),             // 4: jobqueue.JobAck
}
var file_jobqueue_proto_depIdxs = []int32{
	0, // 0: jobqueue.JobQueueService.ClaimJob:input_type -> jobqueue.ClaimJobRequest
	2, // 1: jobqueue.JobQueueService.CompleteJob:input_type -> jobqueue.CompleteJobRequest
	3, // 2: jobqueue.JobQueueService.FailJob:input_type -> jobqueue.FailJobRequest
	1, // 3: jobqueue.JobQueueService.ClaimJob:output_type -> jobqueue.ClaimJobResponse
	4, // 4: jobqueue.JobQueueService.CompleteJob:output_type -> jobqueue.JobAck
	4, // 5: jobqueue.JobQueueService.FailJob:output_type -> jobqueue.JobAck
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobqueue_proto_init() }
func file_jobqueue_proto_init() {
	if File_jobqueue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobqueue_proto_rawDesc), len(file_jobqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobqueue_proto_goTypes,
		DependencyIndexes: file_jobqueue_proto_depIdxs,
		MessageInfos:      file_jobqueue_proto_msgTypes,
	}.Build()
	File_jobqueue_proto = out.File
	file_jobqueue_proto_goTypes = nil
	file_jobqueue_proto_depIdxs = nil
}
