// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: jobqueue.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobQueueService_ClaimJob_FullMethodName    = "/jobqueue.JobQueueService/ClaimJob"
	JobQueueService_CompleteJob_FullMethodName = "/jobqueue.JobQueueService/CompleteJob"
	JobQueueService_FailJob_FullMethodName     = "/jobqueue.JobQueueService/FailJob"
)

// JobQueueServiceClient is the client API for JobQueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobQueueService is the gRPC interface exposed by the Go server.
// C++ (and any other language) workers use this to participate in the queue
// without needing direct database access or knowledge of the schema.
type JobQueueServiceClient interface {
	// ClaimJob atomically claims the next available job.
	// Returns NOT_FOUND if the queue is empty.
	ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*ClaimJobResponse, error)
	// CompleteJob marks a job as successfully completed.
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*JobAck, error)
	// FailJob marks a job failed. The server decides whether to retry
	// based on retry_count, max_retries, and the permanent flag.
	FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*JobAck, error)
}

type jobQueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobQueueServiceClient(cc grpc.ClientConnInterface) JobQueueServiceClient {
	return &jobQueueServiceClient{cc}
}

func (c *jobQueueServiceClient) ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*ClaimJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimJobResponse)
	err := c.cc.Invoke(ctx, JobQueueService_ClaimJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobQueueServiceClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*JobAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobAck)
	err := c.cc.Invoke(ctx, JobQueueService_CompleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobQueueServiceClient) FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*JobAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobAck)
	err := c.cc.Invoke(ctx, JobQueueService_FailJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobQueueServiceServer is the server API for JobQueueService service.
// All implementations must embed UnimplementedJobQueueServiceServer
// for forward compatibility.
//
// JobQueueService is the gRPC interface exposed by the Go server.
// C++ (and any other language) workers use this to participate in the queue
// without needing direct database access or knowledge of the schema.
type JobQueueServiceServer interface {
	// ClaimJob atomically claims the next available job.
	// Returns NOT_FOUND if the queue is empty.
	ClaimJob(context.Context, *ClaimJobRequest) (*ClaimJobResponse, error)
	// CompleteJob marks a job as successfully completed.
	CompleteJob(context.Context, *CompleteJobRequest) (*JobAck, error)
	// FailJob marks a job failed. The server decides whether to retry
	// based on retry_count, max_retries, and the permanent flag.
	FailJob(context.Context, *FailJobRequest) (*JobAck, error)
	mustEmbedUnimplementedJobQueueServiceServer()
}

// UnimplementedJobQueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobQueueServiceServer struct{}

func (UnimplementedJobQueueServiceServer) ClaimJob(context.Context, *ClaimJobRequest) (*ClaimJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimJob not implemented")
}
func (UnimplementedJobQueueServiceServer) CompleteJob(context.Context, *CompleteJobRequest) (*JobAck, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedJobQueueServiceServer) FailJob(context.Context, *FailJobRequest) (*JobAck, error) {
	return nil, status.Error(codes.Unimplemented, "method FailJob not implemented")
}
func (UnimplementedJobQueueServiceServer) mustEmbedUnimplementedJobQueueServiceServer() {}
func (UnimplementedJobQueueServiceServer) testEmbeddedByValue()                         {}

// UnsafeJobQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobQueueServiceServer will
// result in compilation errors.
type UnsafeJobQueueServiceServer interface {
	mustEmbedUnimplementedJobQueueServiceServer()
}

func RegisterJobQueueServiceServer(s grpc.ServiceRegistrar, srv JobQueueServiceServer) {
	// If the following call panics, it indicates UnimplementedJobQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobQueueService_ServiceDesc, srv)
}

func _JobQueueService_ClaimJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobQueueServiceServer).ClaimJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobQueueService_ClaimJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobQueueServiceServer).ClaimJob(ctx, req.(*ClaimJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobQueueService_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobQueueServiceServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobQueueService_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobQueueServiceServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobQueueService_FailJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobQueueServiceServer).FailJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobQueueService_FailJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobQueueServiceServer).FailJob(ctx, req.(*FailJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobQueueService_ServiceDesc is the grpc.ServiceDesc for JobQueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobQueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobqueue.JobQueueService",
	HandlerType: (*JobQueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimJob",
			Handler:    _JobQueueService_ClaimJob_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _JobQueueService_CompleteJob_Handler,
		},
		{
			MethodName: "FailJob",
			Handler:    _JobQueueService_FailJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobqueue.proto",
}
