// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: jobqueue.proto
#ifndef GRPC_jobqueue_2eproto__INCLUDED
#define GRPC_jobqueue_2eproto__INCLUDED

#include "jobqueue.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace jobqueue {

// ── Service ───────────────────────────────────────────────────────────────────
//
// JobQueueService is the gRPC interface exposed by the Go server.
// C++ (and any other language) workers use this to participate in the queue
// without needing direct database access or knowledge of the schema.
class JobQueueService final {
 public:
  static constexpr char const* service_full_name() {
    return "jobqueue.JobQueueService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // ClaimJob atomically claims the next available job.
    // Returns NOT_FOUND if the queue is empty.
    virtual ::grpc::Status ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::jobqueue::ClaimJobResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::ClaimJobResponse>> AsyncClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::ClaimJobResponse>>(AsyncClaimJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::ClaimJobResponse>> PrepareAsyncClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::ClaimJobResponse>>(PrepareAsyncClaimJobRaw(context, request, cq));
    }
    // CompleteJob marks a job as successfully completed.
    virtual ::grpc::Status CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::jobqueue::JobAck* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>> AsyncCompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>>(AsyncCompleteJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>> PrepareAsyncCompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>>(PrepareAsyncCompleteJobRaw(context, request, cq));
    }
    // FailJob marks a job failed. The server decides whether to retry
    // based on retry_count, max_retries, and the permanent flag.
    virtual ::grpc::Status FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::jobqueue::JobAck* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>> AsyncFailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>>(AsyncFailJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>> PrepareAsyncFailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>>(PrepareAsyncFailJobRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // ClaimJob atomically claims the next available job.
      // Returns NOT_FOUND if the queue is empty.
      virtual void ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // CompleteJob marks a job as successfully completed.
      virtual void CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // FailJob marks a job failed. The server decides whether to retry
      // based on retry_count, max_retries, and the permanent flag.
      virtual void FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::ClaimJobResponse>* AsyncClaimJobRaw(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::ClaimJobResponse>* PrepareAsyncClaimJobRaw(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>* AsyncCompleteJobRaw(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>* PrepareAsyncCompleteJobRaw(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>* AsyncFailJobRaw(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::jobqueue::JobAck>* PrepareAsyncFailJobRaw(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::jobqueue::ClaimJobResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>> AsyncClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>>(AsyncClaimJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>> PrepareAsyncClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>>(PrepareAsyncClaimJobRaw(context, request, cq));
    }
    ::grpc::Status CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::jobqueue::JobAck* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>> AsyncCompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>>(AsyncCompleteJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>> PrepareAsyncCompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>>(PrepareAsyncCompleteJobRaw(context, request, cq));
    }
    ::grpc::Status FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::jobqueue::JobAck* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>> AsyncFailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>>(AsyncFailJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>> PrepareAsyncFailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>>(PrepareAsyncFailJobRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response, std::function<void(::grpc::Status)>) override;
      void ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response, std::function<void(::grpc::Status)>) override;
      void CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response, std::function<void(::grpc::Status)>) override;
      void FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>* AsyncClaimJobRaw(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>* PrepareAsyncClaimJobRaw(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* AsyncCompleteJobRaw(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* PrepareAsyncCompleteJobRaw(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* AsyncFailJobRaw(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* PrepareAsyncFailJobRaw(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ClaimJob_;
    const ::grpc::internal::RpcMethod rpcmethod_CompleteJob_;
    const ::grpc::internal::RpcMethod rpcmethod_FailJob_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // ClaimJob atomically claims the next available job.
    // Returns NOT_FOUND if the queue is empty.
    virtual ::grpc::Status ClaimJob(::grpc::ServerContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response);
    // CompleteJob marks a job as successfully completed.
    virtual ::grpc::Status CompleteJob(::grpc::ServerContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response);
    // FailJob marks a job failed. The server decides whether to retry
    // based on retry_count, max_retries, and the permanent flag.
    virtual ::grpc::Status FailJob(::grpc::ServerContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ClaimJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ClaimJob() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ClaimJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimJob(::grpc::ServerContext* /*context*/, const ::jobqueue::ClaimJobRequest* /*request*/, ::jobqueue::ClaimJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClaimJob(::grpc::ServerContext* context, ::jobqueue::ClaimJobRequest* request, ::grpc::ServerAsyncResponseWriter< ::jobqueue::ClaimJobResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CompleteJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CompleteJob() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CompleteJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteJob(::grpc::ServerContext* /*context*/, const ::jobqueue::CompleteJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCompleteJob(::grpc::ServerContext* context, ::jobqueue::CompleteJobRequest* request, ::grpc::ServerAsyncResponseWriter< ::jobqueue::JobAck>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FailJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FailJob() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_FailJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FailJob(::grpc::ServerContext* /*context*/, const ::jobqueue::FailJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFailJob(::grpc::ServerContext* context, ::jobqueue::FailJobRequest* request, ::grpc::ServerAsyncResponseWriter< ::jobqueue::JobAck>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ClaimJob<WithAsyncMethod_CompleteJob<WithAsyncMethod_FailJob<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ClaimJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ClaimJob() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response) { return this->ClaimJob(context, request, response); }));}
    void SetMessageAllocatorFor_ClaimJob(
        ::grpc::MessageAllocator< ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ClaimJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimJob(::grpc::ServerContext* /*context*/, const ::jobqueue::ClaimJobRequest* /*request*/, ::jobqueue::ClaimJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClaimJob(
      ::grpc::CallbackServerContext* /*context*/, const ::jobqueue::ClaimJobRequest* /*request*/, ::jobqueue::ClaimJobResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CompleteJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CompleteJob() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response) { return this->CompleteJob(context, request, response); }));}
    void SetMessageAllocatorFor_CompleteJob(
        ::grpc::MessageAllocator< ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CompleteJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteJob(::grpc::ServerContext* /*context*/, const ::jobqueue::CompleteJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CompleteJob(
      ::grpc::CallbackServerContext* /*context*/, const ::jobqueue::CompleteJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FailJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FailJob() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::jobqueue::FailJobRequest, ::jobqueue::JobAck>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response) { return this->FailJob(context, request, response); }));}
    void SetMessageAllocatorFor_FailJob(
        ::grpc::MessageAllocator< ::jobqueue::FailJobRequest, ::jobqueue::JobAck>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::jobqueue::FailJobRequest, ::jobqueue::JobAck>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FailJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FailJob(::grpc::ServerContext* /*context*/, const ::jobqueue::FailJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FailJob(
      ::grpc::CallbackServerContext* /*context*/, const ::jobqueue::FailJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ClaimJob<WithCallbackMethod_CompleteJob<WithCallbackMethod_FailJob<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ClaimJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ClaimJob() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ClaimJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimJob(::grpc::ServerContext* /*context*/, const ::jobqueue::ClaimJobRequest* /*request*/, ::jobqueue::ClaimJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CompleteJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CompleteJob() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CompleteJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteJob(::grpc::ServerContext* /*context*/, const ::jobqueue::CompleteJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FailJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FailJob() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_FailJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FailJob(::grpc::ServerContext* /*context*/, const ::jobqueue::FailJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ClaimJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ClaimJob() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ClaimJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimJob(::grpc::ServerContext* /*context*/, const ::jobqueue::ClaimJobRequest* /*request*/, ::jobqueue::ClaimJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClaimJob(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CompleteJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CompleteJob() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CompleteJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteJob(::grpc::ServerContext* /*context*/, const ::jobqueue::CompleteJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCompleteJob(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FailJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FailJob() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_FailJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FailJob(::grpc::ServerContext* /*context*/, const ::jobqueue::FailJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFailJob(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ClaimJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ClaimJob() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ClaimJob(context, request, response); }));
    }
    ~WithRawCallbackMethod_ClaimJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimJob(::grpc::ServerContext* /*context*/, const ::jobqueue::ClaimJobRequest* /*request*/, ::jobqueue::ClaimJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClaimJob(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CompleteJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CompleteJob() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CompleteJob(context, request, response); }));
    }
    ~WithRawCallbackMethod_CompleteJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteJob(::grpc::ServerContext* /*context*/, const ::jobqueue::CompleteJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CompleteJob(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FailJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FailJob() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FailJob(context, request, response); }));
    }
    ~WithRawCallbackMethod_FailJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FailJob(::grpc::ServerContext* /*context*/, const ::jobqueue::FailJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FailJob(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ClaimJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ClaimJob() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse>* streamer) {
                       return this->StreamedClaimJob(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ClaimJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ClaimJob(::grpc::ServerContext* /*context*/, const ::jobqueue::ClaimJobRequest* /*request*/, ::jobqueue::ClaimJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedClaimJob(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::jobqueue::ClaimJobRequest,::jobqueue::ClaimJobResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CompleteJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CompleteJob() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck>* streamer) {
                       return this->StreamedCompleteJob(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CompleteJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CompleteJob(::grpc::ServerContext* /*context*/, const ::jobqueue::CompleteJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCompleteJob(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::jobqueue::CompleteJobRequest,::jobqueue::JobAck>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FailJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FailJob() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::jobqueue::FailJobRequest, ::jobqueue::JobAck>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::jobqueue::FailJobRequest, ::jobqueue::JobAck>* streamer) {
                       return this->StreamedFailJob(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FailJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FailJob(::grpc::ServerContext* /*context*/, const ::jobqueue::FailJobRequest* /*request*/, ::jobqueue::JobAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFailJob(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::jobqueue::FailJobRequest,::jobqueue::JobAck>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ClaimJob<WithStreamedUnaryMethod_CompleteJob<WithStreamedUnaryMethod_FailJob<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ClaimJob<WithStreamedUnaryMethod_CompleteJob<WithStreamedUnaryMethod_FailJob<Service > > > StreamedService;
};

}  // namespace jobqueue


#endif  // GRPC_jobqueue_2eproto__INCLUDED
