// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobqueue.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_jobqueue_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_jobqueue_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_jobqueue_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_jobqueue_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_jobqueue_2eproto;
namespace jobqueue {
class ClaimJobRequest;
struct ClaimJobRequestDefaultTypeInternal;
extern ClaimJobRequestDefaultTypeInternal _ClaimJobRequest_default_instance_;
class ClaimJobResponse;
struct ClaimJobResponseDefaultTypeInternal;
extern ClaimJobResponseDefaultTypeInternal _ClaimJobResponse_default_instance_;
class CompleteJobRequest;
struct CompleteJobRequestDefaultTypeInternal;
extern CompleteJobRequestDefaultTypeInternal _CompleteJobRequest_default_instance_;
class FailJobRequest;
struct FailJobRequestDefaultTypeInternal;
extern FailJobRequestDefaultTypeInternal _FailJobRequest_default_instance_;
class JobAck;
struct JobAckDefaultTypeInternal;
extern JobAckDefaultTypeInternal _JobAck_default_instance_;
}  // namespace jobqueue
PROTOBUF_NAMESPACE_OPEN
template<> ::jobqueue::ClaimJobRequest* Arena::CreateMaybeMessage<::jobqueue::ClaimJobRequest>(Arena*);
template<> ::jobqueue::ClaimJobResponse* Arena::CreateMaybeMessage<::jobqueue::ClaimJobResponse>(Arena*);
template<> ::jobqueue::CompleteJobRequest* Arena::CreateMaybeMessage<::jobqueue::CompleteJobRequest>(Arena*);
template<> ::jobqueue::FailJobRequest* Arena::CreateMaybeMessage<::jobqueue::FailJobRequest>(Arena*);
template<> ::jobqueue::JobAck* Arena::CreateMaybeMessage<::jobqueue::JobAck>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace jobqueue {

// ===================================================================

class ClaimJobRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jobqueue.ClaimJobRequest) */ {
 public:
  inline ClaimJobRequest() : ClaimJobRequest(nullptr) {}
  ~ClaimJobRequest() override;
  explicit PROTOBUF_CONSTEXPR ClaimJobRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClaimJobRequest(const ClaimJobRequest& from);
  ClaimJobRequest(ClaimJobRequest&& from) noexcept
    : ClaimJobRequest() {
    *this = ::std::move(from);
  }

  inline ClaimJobRequest& operator=(const ClaimJobRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClaimJobRequest& operator=(ClaimJobRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClaimJobRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClaimJobRequest* internal_default_instance() {
    return reinterpret_cast<const ClaimJobRequest*>(
               &_ClaimJobRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClaimJobRequest& a, ClaimJobRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ClaimJobRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClaimJobRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClaimJobRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClaimJobRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClaimJobRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClaimJobRequest& from) {
    ClaimJobRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClaimJobRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jobqueue.ClaimJobRequest";
  }
  protected:
  explicit ClaimJobRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWorkerIdFieldNumber = 1,
    kQueueNameFieldNumber = 2,
    kLeaseSecondsFieldNumber = 3,
  };
  // string worker_id = 1;
  void clear_worker_id();
  const std::string& worker_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_worker_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_worker_id();
  PROTOBUF_NODISCARD std::string* release_worker_id();
  void set_allocated_worker_id(std::string* worker_id);
  private:
  const std::string& _internal_worker_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_worker_id(const std::string& value);
  std::string* _internal_mutable_worker_id();
  public:

  // string queue_name = 2;
  void clear_queue_name();
  const std::string& queue_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_queue_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_queue_name();
  PROTOBUF_NODISCARD std::string* release_queue_name();
  void set_allocated_queue_name(std::string* queue_name);
  private:
  const std::string& _internal_queue_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_queue_name(const std::string& value);
  std::string* _internal_mutable_queue_name();
  public:

  // int32 lease_seconds = 3;
  void clear_lease_seconds();
  int32_t lease_seconds() const;
  void set_lease_seconds(int32_t value);
  private:
  int32_t _internal_lease_seconds() const;
  void _internal_set_lease_seconds(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:jobqueue.ClaimJobRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr worker_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr queue_name_;
    int32_t lease_seconds_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jobqueue_2eproto;
};
// -------------------------------------------------------------------

class ClaimJobResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jobqueue.ClaimJobResponse) */ {
 public:
  inline ClaimJobResponse() : ClaimJobResponse(nullptr) {}
  ~ClaimJobResponse() override;
  explicit PROTOBUF_CONSTEXPR ClaimJobResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClaimJobResponse(const ClaimJobResponse& from);
  ClaimJobResponse(ClaimJobResponse&& from) noexcept
    : ClaimJobResponse() {
    *this = ::std::move(from);
  }

  inline ClaimJobResponse& operator=(const ClaimJobResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClaimJobResponse& operator=(ClaimJobResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClaimJobResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClaimJobResponse* internal_default_instance() {
    return reinterpret_cast<const ClaimJobResponse*>(
               &_ClaimJobResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ClaimJobResponse& a, ClaimJobResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ClaimJobResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClaimJobResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClaimJobResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClaimJobResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClaimJobResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClaimJobResponse& from) {
    ClaimJobResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClaimJobResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jobqueue.ClaimJobResponse";
  }
  protected:
  explicit ClaimJobResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJobIdFieldNumber = 1,
    kTaskNameFieldNumber = 2,
    kPayloadFieldNumber = 3,
    kPriorityFieldNumber = 4,
    kRetryCountFieldNumber = 5,
    kMaxRetriesFieldNumber = 6,
  };
  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // string task_name = 2;
  void clear_task_name();
  const std::string& task_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_name();
  PROTOBUF_NODISCARD std::string* release_task_name();
  void set_allocated_task_name(std::string* task_name);
  private:
  const std::string& _internal_task_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_name(const std::string& value);
  std::string* _internal_mutable_task_name();
  public:

  // bytes payload = 3;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // int32 priority = 4;
  void clear_priority();
  int32_t priority() const;
  void set_priority(int32_t value);
  private:
  int32_t _internal_priority() const;
  void _internal_set_priority(int32_t value);
  public:

  // int32 retry_count = 5;
  void clear_retry_count();
  int32_t retry_count() const;
  void set_retry_count(int32_t value);
  private:
  int32_t _internal_retry_count() const;
  void _internal_set_retry_count(int32_t value);
  public:

  // int32 max_retries = 6;
  void clear_max_retries();
  int32_t max_retries() const;
  void set_max_retries(int32_t value);
  private:
  int32_t _internal_max_retries() const;
  void _internal_set_max_retries(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:jobqueue.ClaimJobResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    int32_t priority_;
    int32_t retry_count_;
    int32_t max_retries_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jobqueue_2eproto;
};
// -------------------------------------------------------------------

class CompleteJobRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jobqueue.CompleteJobRequest) */ {
 public:
  inline CompleteJobRequest() : CompleteJobRequest(nullptr) {}
  ~CompleteJobRequest() override;
  explicit PROTOBUF_CONSTEXPR CompleteJobRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CompleteJobRequest(const CompleteJobRequest& from);
  CompleteJobRequest(CompleteJobRequest&& from) noexcept
    : CompleteJobRequest() {
    *this = ::std::move(from);
  }

  inline CompleteJobRequest& operator=(const CompleteJobRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompleteJobRequest& operator=(CompleteJobRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CompleteJobRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CompleteJobRequest* internal_default_instance() {
    return reinterpret_cast<const CompleteJobRequest*>(
               &_CompleteJobRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CompleteJobRequest& a, CompleteJobRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CompleteJobRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompleteJobRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CompleteJobRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CompleteJobRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CompleteJobRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CompleteJobRequest& from) {
    CompleteJobRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompleteJobRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jobqueue.CompleteJobRequest";
  }
  protected:
  explicit CompleteJobRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJobIdFieldNumber = 1,
    kWorkerIdFieldNumber = 2,
  };
  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // string worker_id = 2;
  void clear_worker_id();
  const std::string& worker_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_worker_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_worker_id();
  PROTOBUF_NODISCARD std::string* release_worker_id();
  void set_allocated_worker_id(std::string* worker_id);
  private:
  const std::string& _internal_worker_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_worker_id(const std::string& value);
  std::string* _internal_mutable_worker_id();
  public:

  // @@protoc_insertion_point(class_scope:jobqueue.CompleteJobRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr worker_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jobqueue_2eproto;
};
// -------------------------------------------------------------------

class FailJobRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jobqueue.FailJobRequest) */ {
 public:
  inline FailJobRequest() : FailJobRequest(nullptr) {}
  ~FailJobRequest() override;
  explicit PROTOBUF_CONSTEXPR FailJobRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FailJobRequest(const FailJobRequest& from);
  FailJobRequest(FailJobRequest&& from) noexcept
    : FailJobRequest() {
    *this = ::std::move(from);
  }

  inline FailJobRequest& operator=(const FailJobRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FailJobRequest& operator=(FailJobRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FailJobRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FailJobRequest* internal_default_instance() {
    return reinterpret_cast<const FailJobRequest*>(
               &_FailJobRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FailJobRequest& a, FailJobRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FailJobRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FailJobRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FailJobRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FailJobRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FailJobRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FailJobRequest& from) {
    FailJobRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FailJobRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jobqueue.FailJobRequest";
  }
  protected:
  explicit FailJobRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJobIdFieldNumber = 1,
    kWorkerIdFieldNumber = 2,
    kErrorMsgFieldNumber = 3,
    kPermanentFieldNumber = 4,
    kRetryCountFieldNumber = 5,
  };
  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // string worker_id = 2;
  void clear_worker_id();
  const std::string& worker_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_worker_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_worker_id();
  PROTOBUF_NODISCARD std::string* release_worker_id();
  void set_allocated_worker_id(std::string* worker_id);
  private:
  const std::string& _internal_worker_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_worker_id(const std::string& value);
  std::string* _internal_mutable_worker_id();
  public:

  // string error_msg = 3;
  void clear_error_msg();
  const std::string& error_msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_msg();
  PROTOBUF_NODISCARD std::string* release_error_msg();
  void set_allocated_error_msg(std::string* error_msg);
  private:
  const std::string& _internal_error_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_msg(const std::string& value);
  std::string* _internal_mutable_error_msg();
  public:

  // bool permanent = 4;
  void clear_permanent();
  bool permanent() const;
  void set_permanent(bool value);
  private:
  bool _internal_permanent() const;
  void _internal_set_permanent(bool value);
  public:

  // int32 retry_count = 5;
  void clear_retry_count();
  int32_t retry_count() const;
  void set_retry_count(int32_t value);
  private:
  int32_t _internal_retry_count() const;
  void _internal_set_retry_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:jobqueue.FailJobRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr worker_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_msg_;
    bool permanent_;
    int32_t retry_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jobqueue_2eproto;
};
// -------------------------------------------------------------------

class JobAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jobqueue.JobAck) */ {
 public:
  inline JobAck() : JobAck(nullptr) {}
  ~JobAck() override;
  explicit PROTOBUF_CONSTEXPR JobAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JobAck(const JobAck& from);
  JobAck(JobAck&& from) noexcept
    : JobAck() {
    *this = ::std::move(from);
  }

  inline JobAck& operator=(const JobAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline JobAck& operator=(JobAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JobAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const JobAck* internal_default_instance() {
    return reinterpret_cast<const JobAck*>(
               &_JobAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(JobAck& a, JobAck& b) {
    a.Swap(&b);
  }
  inline void Swap(JobAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JobAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JobAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JobAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JobAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JobAck& from) {
    JobAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JobAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jobqueue.JobAck";
  }
  protected:
  explicit JobAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJobIdFieldNumber = 1,
  };
  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // @@protoc_insertion_point(class_scope:jobqueue.JobAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jobqueue_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClaimJobRequest

// string worker_id = 1;
inline void ClaimJobRequest::clear_worker_id() {
  _impl_.worker_id_.ClearToEmpty();
}
inline const std::string& ClaimJobRequest::worker_id() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobRequest.worker_id)
  return _internal_worker_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClaimJobRequest::set_worker_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.worker_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobRequest.worker_id)
}
inline std::string* ClaimJobRequest::mutable_worker_id() {
  std::string* _s = _internal_mutable_worker_id();
  // @@protoc_insertion_point(field_mutable:jobqueue.ClaimJobRequest.worker_id)
  return _s;
}
inline const std::string& ClaimJobRequest::_internal_worker_id() const {
  return _impl_.worker_id_.Get();
}
inline void ClaimJobRequest::_internal_set_worker_id(const std::string& value) {
  
  _impl_.worker_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ClaimJobRequest::_internal_mutable_worker_id() {
  
  return _impl_.worker_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ClaimJobRequest::release_worker_id() {
  // @@protoc_insertion_point(field_release:jobqueue.ClaimJobRequest.worker_id)
  return _impl_.worker_id_.Release();
}
inline void ClaimJobRequest::set_allocated_worker_id(std::string* worker_id) {
  if (worker_id != nullptr) {
    
  } else {
    
  }
  _impl_.worker_id_.SetAllocated(worker_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.worker_id_.IsDefault()) {
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.ClaimJobRequest.worker_id)
}

// string queue_name = 2;
inline void ClaimJobRequest::clear_queue_name() {
  _impl_.queue_name_.ClearToEmpty();
}
inline const std::string& ClaimJobRequest::queue_name() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobRequest.queue_name)
  return _internal_queue_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClaimJobRequest::set_queue_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.queue_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobRequest.queue_name)
}
inline std::string* ClaimJobRequest::mutable_queue_name() {
  std::string* _s = _internal_mutable_queue_name();
  // @@protoc_insertion_point(field_mutable:jobqueue.ClaimJobRequest.queue_name)
  return _s;
}
inline const std::string& ClaimJobRequest::_internal_queue_name() const {
  return _impl_.queue_name_.Get();
}
inline void ClaimJobRequest::_internal_set_queue_name(const std::string& value) {
  
  _impl_.queue_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ClaimJobRequest::_internal_mutable_queue_name() {
  
  return _impl_.queue_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ClaimJobRequest::release_queue_name() {
  // @@protoc_insertion_point(field_release:jobqueue.ClaimJobRequest.queue_name)
  return _impl_.queue_name_.Release();
}
inline void ClaimJobRequest::set_allocated_queue_name(std::string* queue_name) {
  if (queue_name != nullptr) {
    
  } else {
    
  }
  _impl_.queue_name_.SetAllocated(queue_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.queue_name_.IsDefault()) {
    _impl_.queue_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.ClaimJobRequest.queue_name)
}

// int32 lease_seconds = 3;
inline void ClaimJobRequest::clear_lease_seconds() {
  _impl_.lease_seconds_ = 0;
}
inline int32_t ClaimJobRequest::_internal_lease_seconds() const {
  return _impl_.lease_seconds_;
}
inline int32_t ClaimJobRequest::lease_seconds() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobRequest.lease_seconds)
  return _internal_lease_seconds();
}
inline void ClaimJobRequest::_internal_set_lease_seconds(int32_t value) {
  
  _impl_.lease_seconds_ = value;
}
inline void ClaimJobRequest::set_lease_seconds(int32_t value) {
  _internal_set_lease_seconds(value);
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobRequest.lease_seconds)
}

// -------------------------------------------------------------------

// ClaimJobResponse

// string job_id = 1;
inline void ClaimJobResponse::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& ClaimJobResponse::job_id() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobResponse.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClaimJobResponse::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobResponse.job_id)
}
inline std::string* ClaimJobResponse::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:jobqueue.ClaimJobResponse.job_id)
  return _s;
}
inline const std::string& ClaimJobResponse::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void ClaimJobResponse::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ClaimJobResponse::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ClaimJobResponse::release_job_id() {
  // @@protoc_insertion_point(field_release:jobqueue.ClaimJobResponse.job_id)
  return _impl_.job_id_.Release();
}
inline void ClaimJobResponse::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.ClaimJobResponse.job_id)
}

// string task_name = 2;
inline void ClaimJobResponse::clear_task_name() {
  _impl_.task_name_.ClearToEmpty();
}
inline const std::string& ClaimJobResponse::task_name() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobResponse.task_name)
  return _internal_task_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClaimJobResponse::set_task_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.task_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobResponse.task_name)
}
inline std::string* ClaimJobResponse::mutable_task_name() {
  std::string* _s = _internal_mutable_task_name();
  // @@protoc_insertion_point(field_mutable:jobqueue.ClaimJobResponse.task_name)
  return _s;
}
inline const std::string& ClaimJobResponse::_internal_task_name() const {
  return _impl_.task_name_.Get();
}
inline void ClaimJobResponse::_internal_set_task_name(const std::string& value) {
  
  _impl_.task_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ClaimJobResponse::_internal_mutable_task_name() {
  
  return _impl_.task_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ClaimJobResponse::release_task_name() {
  // @@protoc_insertion_point(field_release:jobqueue.ClaimJobResponse.task_name)
  return _impl_.task_name_.Release();
}
inline void ClaimJobResponse::set_allocated_task_name(std::string* task_name) {
  if (task_name != nullptr) {
    
  } else {
    
  }
  _impl_.task_name_.SetAllocated(task_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.task_name_.IsDefault()) {
    _impl_.task_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.ClaimJobResponse.task_name)
}

// bytes payload = 3;
inline void ClaimJobResponse::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& ClaimJobResponse::payload() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobResponse.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClaimJobResponse::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobResponse.payload)
}
inline std::string* ClaimJobResponse::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:jobqueue.ClaimJobResponse.payload)
  return _s;
}
inline const std::string& ClaimJobResponse::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void ClaimJobResponse::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* ClaimJobResponse::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* ClaimJobResponse::release_payload() {
  // @@protoc_insertion_point(field_release:jobqueue.ClaimJobResponse.payload)
  return _impl_.payload_.Release();
}
inline void ClaimJobResponse::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.ClaimJobResponse.payload)
}

// int32 priority = 4;
inline void ClaimJobResponse::clear_priority() {
  _impl_.priority_ = 0;
}
inline int32_t ClaimJobResponse::_internal_priority() const {
  return _impl_.priority_;
}
inline int32_t ClaimJobResponse::priority() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobResponse.priority)
  return _internal_priority();
}
inline void ClaimJobResponse::_internal_set_priority(int32_t value) {
  
  _impl_.priority_ = value;
}
inline void ClaimJobResponse::set_priority(int32_t value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobResponse.priority)
}

// int32 retry_count = 5;
inline void ClaimJobResponse::clear_retry_count() {
  _impl_.retry_count_ = 0;
}
inline int32_t ClaimJobResponse::_internal_retry_count() const {
  return _impl_.retry_count_;
}
inline int32_t ClaimJobResponse::retry_count() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobResponse.retry_count)
  return _internal_retry_count();
}
inline void ClaimJobResponse::_internal_set_retry_count(int32_t value) {
  
  _impl_.retry_count_ = value;
}
inline void ClaimJobResponse::set_retry_count(int32_t value) {
  _internal_set_retry_count(value);
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobResponse.retry_count)
}

// int32 max_retries = 6;
inline void ClaimJobResponse::clear_max_retries() {
  _impl_.max_retries_ = 0;
}
inline int32_t ClaimJobResponse::_internal_max_retries() const {
  return _impl_.max_retries_;
}
inline int32_t ClaimJobResponse::max_retries() const {
  // @@protoc_insertion_point(field_get:jobqueue.ClaimJobResponse.max_retries)
  return _internal_max_retries();
}
inline void ClaimJobResponse::_internal_set_max_retries(int32_t value) {
  
  _impl_.max_retries_ = value;
}
inline void ClaimJobResponse::set_max_retries(int32_t value) {
  _internal_set_max_retries(value);
  // @@protoc_insertion_point(field_set:jobqueue.ClaimJobResponse.max_retries)
}

// -------------------------------------------------------------------

// CompleteJobRequest

// string job_id = 1;
inline void CompleteJobRequest::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& CompleteJobRequest::job_id() const {
  // @@protoc_insertion_point(field_get:jobqueue.CompleteJobRequest.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CompleteJobRequest::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.CompleteJobRequest.job_id)
}
inline std::string* CompleteJobRequest::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:jobqueue.CompleteJobRequest.job_id)
  return _s;
}
inline const std::string& CompleteJobRequest::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void CompleteJobRequest::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CompleteJobRequest::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CompleteJobRequest::release_job_id() {
  // @@protoc_insertion_point(field_release:jobqueue.CompleteJobRequest.job_id)
  return _impl_.job_id_.Release();
}
inline void CompleteJobRequest::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.CompleteJobRequest.job_id)
}

// string worker_id = 2;
inline void CompleteJobRequest::clear_worker_id() {
  _impl_.worker_id_.ClearToEmpty();
}
inline const std::string& CompleteJobRequest::worker_id() const {
  // @@protoc_insertion_point(field_get:jobqueue.CompleteJobRequest.worker_id)
  return _internal_worker_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CompleteJobRequest::set_worker_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.worker_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.CompleteJobRequest.worker_id)
}
inline std::string* CompleteJobRequest::mutable_worker_id() {
  std::string* _s = _internal_mutable_worker_id();
  // @@protoc_insertion_point(field_mutable:jobqueue.CompleteJobRequest.worker_id)
  return _s;
}
inline const std::string& CompleteJobRequest::_internal_worker_id() const {
  return _impl_.worker_id_.Get();
}
inline void CompleteJobRequest::_internal_set_worker_id(const std::string& value) {
  
  _impl_.worker_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CompleteJobRequest::_internal_mutable_worker_id() {
  
  return _impl_.worker_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CompleteJobRequest::release_worker_id() {
  // @@protoc_insertion_point(field_release:jobqueue.CompleteJobRequest.worker_id)
  return _impl_.worker_id_.Release();
}
inline void CompleteJobRequest::set_allocated_worker_id(std::string* worker_id) {
  if (worker_id != nullptr) {
    
  } else {
    
  }
  _impl_.worker_id_.SetAllocated(worker_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.worker_id_.IsDefault()) {
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.CompleteJobRequest.worker_id)
}

// -------------------------------------------------------------------

// FailJobRequest

// string job_id = 1;
inline void FailJobRequest::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& FailJobRequest::job_id() const {
  // @@protoc_insertion_point(field_get:jobqueue.FailJobRequest.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FailJobRequest::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.FailJobRequest.job_id)
}
inline std::string* FailJobRequest::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:jobqueue.FailJobRequest.job_id)
  return _s;
}
inline const std::string& FailJobRequest::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void FailJobRequest::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* FailJobRequest::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* FailJobRequest::release_job_id() {
  // @@protoc_insertion_point(field_release:jobqueue.FailJobRequest.job_id)
  return _impl_.job_id_.Release();
}
inline void FailJobRequest::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.FailJobRequest.job_id)
}

// string worker_id = 2;
inline void FailJobRequest::clear_worker_id() {
  _impl_.worker_id_.ClearToEmpty();
}
inline const std::string& FailJobRequest::worker_id() const {
  // @@protoc_insertion_point(field_get:jobqueue.FailJobRequest.worker_id)
  return _internal_worker_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FailJobRequest::set_worker_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.worker_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.FailJobRequest.worker_id)
}
inline std::string* FailJobRequest::mutable_worker_id() {
  std::string* _s = _internal_mutable_worker_id();
  // @@protoc_insertion_point(field_mutable:jobqueue.FailJobRequest.worker_id)
  return _s;
}
inline const std::string& FailJobRequest::_internal_worker_id() const {
  return _impl_.worker_id_.Get();
}
inline void FailJobRequest::_internal_set_worker_id(const std::string& value) {
  
  _impl_.worker_id_.Set(value, GetArenaForAllocation());
}
inline std::string* FailJobRequest::_internal_mutable_worker_id() {
  
  return _impl_.worker_id_.Mutable(GetArenaForAllocation());
}
inline std::string* FailJobRequest::release_worker_id() {
  // @@protoc_insertion_point(field_release:jobqueue.FailJobRequest.worker_id)
  return _impl_.worker_id_.Release();
}
inline void FailJobRequest::set_allocated_worker_id(std::string* worker_id) {
  if (worker_id != nullptr) {
    
  } else {
    
  }
  _impl_.worker_id_.SetAllocated(worker_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.worker_id_.IsDefault()) {
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.FailJobRequest.worker_id)
}

// string error_msg = 3;
inline void FailJobRequest::clear_error_msg() {
  _impl_.error_msg_.ClearToEmpty();
}
inline const std::string& FailJobRequest::error_msg() const {
  // @@protoc_insertion_point(field_get:jobqueue.FailJobRequest.error_msg)
  return _internal_error_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FailJobRequest::set_error_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.FailJobRequest.error_msg)
}
inline std::string* FailJobRequest::mutable_error_msg() {
  std::string* _s = _internal_mutable_error_msg();
  // @@protoc_insertion_point(field_mutable:jobqueue.FailJobRequest.error_msg)
  return _s;
}
inline const std::string& FailJobRequest::_internal_error_msg() const {
  return _impl_.error_msg_.Get();
}
inline void FailJobRequest::_internal_set_error_msg(const std::string& value) {
  
  _impl_.error_msg_.Set(value, GetArenaForAllocation());
}
inline std::string* FailJobRequest::_internal_mutable_error_msg() {
  
  return _impl_.error_msg_.Mutable(GetArenaForAllocation());
}
inline std::string* FailJobRequest::release_error_msg() {
  // @@protoc_insertion_point(field_release:jobqueue.FailJobRequest.error_msg)
  return _impl_.error_msg_.Release();
}
inline void FailJobRequest::set_allocated_error_msg(std::string* error_msg) {
  if (error_msg != nullptr) {
    
  } else {
    
  }
  _impl_.error_msg_.SetAllocated(error_msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_msg_.IsDefault()) {
    _impl_.error_msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.FailJobRequest.error_msg)
}

// bool permanent = 4;
inline void FailJobRequest::clear_permanent() {
  _impl_.permanent_ = false;
}
inline bool FailJobRequest::_internal_permanent() const {
  return _impl_.permanent_;
}
inline bool FailJobRequest::permanent() const {
  // @@protoc_insertion_point(field_get:jobqueue.FailJobRequest.permanent)
  return _internal_permanent();
}
inline void FailJobRequest::_internal_set_permanent(bool value) {
  
  _impl_.permanent_ = value;
}
inline void FailJobRequest::set_permanent(bool value) {
  _internal_set_permanent(value);
  // @@protoc_insertion_point(field_set:jobqueue.FailJobRequest.permanent)
}

// int32 retry_count = 5;
inline void FailJobRequest::clear_retry_count() {
  _impl_.retry_count_ = 0;
}
inline int32_t FailJobRequest::_internal_retry_count() const {
  return _impl_.retry_count_;
}
inline int32_t FailJobRequest::retry_count() const {
  // @@protoc_insertion_point(field_get:jobqueue.FailJobRequest.retry_count)
  return _internal_retry_count();
}
inline void FailJobRequest::_internal_set_retry_count(int32_t value) {
  
  _impl_.retry_count_ = value;
}
inline void FailJobRequest::set_retry_count(int32_t value) {
  _internal_set_retry_count(value);
  // @@protoc_insertion_point(field_set:jobqueue.FailJobRequest.retry_count)
}

// -------------------------------------------------------------------

// JobAck

// string job_id = 1;
inline void JobAck::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& JobAck::job_id() const {
  // @@protoc_insertion_point(field_get:jobqueue.JobAck.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JobAck::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jobqueue.JobAck.job_id)
}
inline std::string* JobAck::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:jobqueue.JobAck.job_id)
  return _s;
}
inline const std::string& JobAck::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void JobAck::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* JobAck::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* JobAck::release_job_id() {
  // @@protoc_insertion_point(field_release:jobqueue.JobAck.job_id)
  return _impl_.job_id_.Release();
}
inline void JobAck::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jobqueue.JobAck.job_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace jobqueue

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_jobqueue_2eproto
