// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: jobqueue.proto

#include "jobqueue.pb.h"
#include "jobqueue.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace jobqueue {

static const char* JobQueueService_method_names[] = {
  "/jobqueue.JobQueueService/ClaimJob",
  "/jobqueue.JobQueueService/CompleteJob",
  "/jobqueue.JobQueueService/FailJob",
};

std::unique_ptr< JobQueueService::Stub> JobQueueService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< JobQueueService::Stub> stub(new JobQueueService::Stub(channel, options));
  return stub;
}

JobQueueService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ClaimJob_(JobQueueService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CompleteJob_(JobQueueService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FailJob_(JobQueueService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status JobQueueService::Stub::ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::jobqueue::ClaimJobResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ClaimJob_, context, request, response);
}

void JobQueueService::Stub::async::ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClaimJob_, context, request, response, std::move(f));
}

void JobQueueService::Stub::async::ClaimJob(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClaimJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>* JobQueueService::Stub::PrepareAsyncClaimJobRaw(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::jobqueue::ClaimJobResponse, ::jobqueue::ClaimJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ClaimJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::jobqueue::ClaimJobResponse>* JobQueueService::Stub::AsyncClaimJobRaw(::grpc::ClientContext* context, const ::jobqueue::ClaimJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClaimJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobQueueService::Stub::CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::jobqueue::JobAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CompleteJob_, context, request, response);
}

void JobQueueService::Stub::async::CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteJob_, context, request, response, std::move(f));
}

void JobQueueService::Stub::async::CompleteJob(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* JobQueueService::Stub::PrepareAsyncCompleteJobRaw(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::jobqueue::JobAck, ::jobqueue::CompleteJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CompleteJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* JobQueueService::Stub::AsyncCompleteJobRaw(::grpc::ClientContext* context, const ::jobqueue::CompleteJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCompleteJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status JobQueueService::Stub::FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::jobqueue::JobAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::jobqueue::FailJobRequest, ::jobqueue::JobAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FailJob_, context, request, response);
}

void JobQueueService::Stub::async::FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::jobqueue::FailJobRequest, ::jobqueue::JobAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FailJob_, context, request, response, std::move(f));
}

void JobQueueService::Stub::async::FailJob(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FailJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* JobQueueService::Stub::PrepareAsyncFailJobRaw(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::jobqueue::JobAck, ::jobqueue::FailJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FailJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::jobqueue::JobAck>* JobQueueService::Stub::AsyncFailJobRaw(::grpc::ClientContext* context, const ::jobqueue::FailJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFailJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

JobQueueService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobQueueService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobQueueService::Service, ::jobqueue::ClaimJobRequest, ::jobqueue::ClaimJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobQueueService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::jobqueue::ClaimJobRequest* req,
             ::jobqueue::ClaimJobResponse* resp) {
               return service->ClaimJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobQueueService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobQueueService::Service, ::jobqueue::CompleteJobRequest, ::jobqueue::JobAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobQueueService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::jobqueue::CompleteJobRequest* req,
             ::jobqueue::JobAck* resp) {
               return service->CompleteJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JobQueueService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JobQueueService::Service, ::jobqueue::FailJobRequest, ::jobqueue::JobAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JobQueueService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::jobqueue::FailJobRequest* req,
             ::jobqueue::JobAck* resp) {
               return service->FailJob(ctx, req, resp);
             }, this)));
}

JobQueueService::Service::~Service() {
}

::grpc::Status JobQueueService::Service::ClaimJob(::grpc::ServerContext* context, const ::jobqueue::ClaimJobRequest* request, ::jobqueue::ClaimJobResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobQueueService::Service::CompleteJob(::grpc::ServerContext* context, const ::jobqueue::CompleteJobRequest* request, ::jobqueue::JobAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status JobQueueService::Service::FailJob(::grpc::ServerContext* context, const ::jobqueue::FailJobRequest* request, ::jobqueue::JobAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace jobqueue

