// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobqueue.proto

#include "jobqueue.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace jobqueue {
PROTOBUF_CONSTEXPR ClaimJobRequest::ClaimJobRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.worker_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.queue_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lease_seconds_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClaimJobRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClaimJobRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClaimJobRequestDefaultTypeInternal() {}
  union {
    ClaimJobRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClaimJobRequestDefaultTypeInternal _ClaimJobRequest_default_instance_;
PROTOBUF_CONSTEXPR ClaimJobResponse::ClaimJobResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.task_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.payload_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.priority_)*/0
  , /*decltype(_impl_.retry_count_)*/0
  , /*decltype(_impl_.max_retries_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClaimJobResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClaimJobResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClaimJobResponseDefaultTypeInternal() {}
  union {
    ClaimJobResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClaimJobResponseDefaultTypeInternal _ClaimJobResponse_default_instance_;
PROTOBUF_CONSTEXPR CompleteJobRequest::CompleteJobRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.worker_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CompleteJobRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompleteJobRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompleteJobRequestDefaultTypeInternal() {}
  union {
    CompleteJobRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompleteJobRequestDefaultTypeInternal _CompleteJobRequest_default_instance_;
PROTOBUF_CONSTEXPR FailJobRequest::FailJobRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.worker_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_msg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.permanent_)*/false
  , /*decltype(_impl_.retry_count_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FailJobRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FailJobRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FailJobRequestDefaultTypeInternal() {}
  union {
    FailJobRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FailJobRequestDefaultTypeInternal _FailJobRequest_default_instance_;
PROTOBUF_CONSTEXPR JobAck::JobAck(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct JobAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JobAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JobAckDefaultTypeInternal() {}
  union {
    JobAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JobAckDefaultTypeInternal _JobAck_default_instance_;
}  // namespace jobqueue
static ::_pb::Metadata file_level_metadata_jobqueue_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_jobqueue_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_jobqueue_2eproto = nullptr;

const uint32_t TableStruct_jobqueue_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobRequest, _impl_.worker_id_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobRequest, _impl_.queue_name_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobRequest, _impl_.lease_seconds_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobResponse, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobResponse, _impl_.task_name_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobResponse, _impl_.payload_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobResponse, _impl_.priority_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobResponse, _impl_.retry_count_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::ClaimJobResponse, _impl_.max_retries_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jobqueue::CompleteJobRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jobqueue::CompleteJobRequest, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::CompleteJobRequest, _impl_.worker_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jobqueue::FailJobRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jobqueue::FailJobRequest, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::FailJobRequest, _impl_.worker_id_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::FailJobRequest, _impl_.error_msg_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::FailJobRequest, _impl_.permanent_),
  PROTOBUF_FIELD_OFFSET(::jobqueue::FailJobRequest, _impl_.retry_count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jobqueue::JobAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jobqueue::JobAck, _impl_.job_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::jobqueue::ClaimJobRequest)},
  { 9, -1, -1, sizeof(::jobqueue::ClaimJobResponse)},
  { 21, -1, -1, sizeof(::jobqueue::CompleteJobRequest)},
  { 29, -1, -1, sizeof(::jobqueue::FailJobRequest)},
  { 40, -1, -1, sizeof(::jobqueue::JobAck)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::jobqueue::_ClaimJobRequest_default_instance_._instance,
  &::jobqueue::_ClaimJobResponse_default_instance_._instance,
  &::jobqueue::_CompleteJobRequest_default_instance_._instance,
  &::jobqueue::_FailJobRequest_default_instance_._instance,
  &::jobqueue::_JobAck_default_instance_._instance,
};

const char descriptor_table_protodef_jobqueue_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016jobqueue.proto\022\010jobqueue\"O\n\017ClaimJobRe"
  "quest\022\021\n\tworker_id\030\001 \001(\t\022\022\n\nqueue_name\030\002"
  " \001(\t\022\025\n\rlease_seconds\030\003 \001(\005\"\202\001\n\020ClaimJob"
  "Response\022\016\n\006job_id\030\001 \001(\t\022\021\n\ttask_name\030\002 "
  "\001(\t\022\017\n\007payload\030\003 \001(\014\022\020\n\010priority\030\004 \001(\005\022\023"
  "\n\013retry_count\030\005 \001(\005\022\023\n\013max_retries\030\006 \001(\005"
  "\"7\n\022CompleteJobRequest\022\016\n\006job_id\030\001 \001(\t\022\021"
  "\n\tworker_id\030\002 \001(\t\"n\n\016FailJobRequest\022\016\n\006j"
  "ob_id\030\001 \001(\t\022\021\n\tworker_id\030\002 \001(\t\022\021\n\terror_"
  "msg\030\003 \001(\t\022\021\n\tpermanent\030\004 \001(\010\022\023\n\013retry_co"
  "unt\030\005 \001(\005\"\030\n\006JobAck\022\016\n\006job_id\030\001 \001(\t2\312\001\n\017"
  "JobQueueService\022A\n\010ClaimJob\022\031.jobqueue.C"
  "laimJobRequest\032\032.jobqueue.ClaimJobRespon"
  "se\022=\n\013CompleteJob\022\034.jobqueue.CompleteJob"
  "Request\032\020.jobqueue.JobAck\0225\n\007FailJob\022\030.j"
  "obqueue.FailJobRequest\032\020.jobqueue.JobAck"
  "B3Z1github.com/distributed-job-queue/int"
  "ernal/grpc/pbb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_jobqueue_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_jobqueue_2eproto = {
    false, false, 701, descriptor_table_protodef_jobqueue_2eproto,
    "jobqueue.proto",
    &descriptor_table_jobqueue_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_jobqueue_2eproto::offsets,
    file_level_metadata_jobqueue_2eproto, file_level_enum_descriptors_jobqueue_2eproto,
    file_level_service_descriptors_jobqueue_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_jobqueue_2eproto_getter() {
  return &descriptor_table_jobqueue_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_jobqueue_2eproto(&descriptor_table_jobqueue_2eproto);
namespace jobqueue {

// ===================================================================

class ClaimJobRequest::_Internal {
 public:
};

ClaimJobRequest::ClaimJobRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jobqueue.ClaimJobRequest)
}
ClaimJobRequest::ClaimJobRequest(const ClaimJobRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClaimJobRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.worker_id_){}
    , decltype(_impl_.queue_name_){}
    , decltype(_impl_.lease_seconds_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_worker_id().empty()) {
    _this->_impl_.worker_id_.Set(from._internal_worker_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.queue_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.queue_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_queue_name().empty()) {
    _this->_impl_.queue_name_.Set(from._internal_queue_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.lease_seconds_ = from._impl_.lease_seconds_;
  // @@protoc_insertion_point(copy_constructor:jobqueue.ClaimJobRequest)
}

inline void ClaimJobRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.worker_id_){}
    , decltype(_impl_.queue_name_){}
    , decltype(_impl_.lease_seconds_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.queue_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.queue_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ClaimJobRequest::~ClaimJobRequest() {
  // @@protoc_insertion_point(destructor:jobqueue.ClaimJobRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClaimJobRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.worker_id_.Destroy();
  _impl_.queue_name_.Destroy();
}

void ClaimJobRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClaimJobRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:jobqueue.ClaimJobRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.worker_id_.ClearToEmpty();
  _impl_.queue_name_.ClearToEmpty();
  _impl_.lease_seconds_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClaimJobRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string worker_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_worker_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.ClaimJobRequest.worker_id"));
        } else
          goto handle_unusual;
        continue;
      // string queue_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_queue_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.ClaimJobRequest.queue_name"));
        } else
          goto handle_unusual;
        continue;
      // int32 lease_seconds = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.lease_seconds_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClaimJobRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jobqueue.ClaimJobRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_worker_id().data(), static_cast<int>(this->_internal_worker_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.ClaimJobRequest.worker_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_worker_id(), target);
  }

  // string queue_name = 2;
  if (!this->_internal_queue_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_queue_name().data(), static_cast<int>(this->_internal_queue_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.ClaimJobRequest.queue_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_queue_name(), target);
  }

  // int32 lease_seconds = 3;
  if (this->_internal_lease_seconds() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_lease_seconds(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jobqueue.ClaimJobRequest)
  return target;
}

size_t ClaimJobRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jobqueue.ClaimJobRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_worker_id());
  }

  // string queue_name = 2;
  if (!this->_internal_queue_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_queue_name());
  }

  // int32 lease_seconds = 3;
  if (this->_internal_lease_seconds() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_lease_seconds());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClaimJobRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClaimJobRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClaimJobRequest::GetClassData() const { return &_class_data_; }


void ClaimJobRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClaimJobRequest*>(&to_msg);
  auto& from = static_cast<const ClaimJobRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jobqueue.ClaimJobRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_worker_id().empty()) {
    _this->_internal_set_worker_id(from._internal_worker_id());
  }
  if (!from._internal_queue_name().empty()) {
    _this->_internal_set_queue_name(from._internal_queue_name());
  }
  if (from._internal_lease_seconds() != 0) {
    _this->_internal_set_lease_seconds(from._internal_lease_seconds());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClaimJobRequest::CopyFrom(const ClaimJobRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jobqueue.ClaimJobRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClaimJobRequest::IsInitialized() const {
  return true;
}

void ClaimJobRequest::InternalSwap(ClaimJobRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.worker_id_, lhs_arena,
      &other->_impl_.worker_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.queue_name_, lhs_arena,
      &other->_impl_.queue_name_, rhs_arena
  );
  swap(_impl_.lease_seconds_, other->_impl_.lease_seconds_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClaimJobRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jobqueue_2eproto_getter, &descriptor_table_jobqueue_2eproto_once,
      file_level_metadata_jobqueue_2eproto[0]);
}

// ===================================================================

class ClaimJobResponse::_Internal {
 public:
};

ClaimJobResponse::ClaimJobResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jobqueue.ClaimJobResponse)
}
ClaimJobResponse::ClaimJobResponse(const ClaimJobResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClaimJobResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.task_name_){}
    , decltype(_impl_.payload_){}
    , decltype(_impl_.priority_){}
    , decltype(_impl_.retry_count_){}
    , decltype(_impl_.max_retries_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.task_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.task_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_task_name().empty()) {
    _this->_impl_.task_name_.Set(from._internal_task_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_payload().empty()) {
    _this->_impl_.payload_.Set(from._internal_payload(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.priority_, &from._impl_.priority_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_retries_) -
    reinterpret_cast<char*>(&_impl_.priority_)) + sizeof(_impl_.max_retries_));
  // @@protoc_insertion_point(copy_constructor:jobqueue.ClaimJobResponse)
}

inline void ClaimJobResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.task_name_){}
    , decltype(_impl_.payload_){}
    , decltype(_impl_.priority_){0}
    , decltype(_impl_.retry_count_){0}
    , decltype(_impl_.max_retries_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.task_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.task_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ClaimJobResponse::~ClaimJobResponse() {
  // @@protoc_insertion_point(destructor:jobqueue.ClaimJobResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClaimJobResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.job_id_.Destroy();
  _impl_.task_name_.Destroy();
  _impl_.payload_.Destroy();
}

void ClaimJobResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClaimJobResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:jobqueue.ClaimJobResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  _impl_.task_name_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  ::memset(&_impl_.priority_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.max_retries_) -
      reinterpret_cast<char*>(&_impl_.priority_)) + sizeof(_impl_.max_retries_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClaimJobResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.ClaimJobResponse.job_id"));
        } else
          goto handle_unusual;
        continue;
      // string task_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_task_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.ClaimJobResponse.task_name"));
        } else
          goto handle_unusual;
        continue;
      // bytes payload = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 priority = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.priority_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 retry_count = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.retry_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 max_retries = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.max_retries_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClaimJobResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jobqueue.ClaimJobResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.ClaimJobResponse.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // string task_name = 2;
  if (!this->_internal_task_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_task_name().data(), static_cast<int>(this->_internal_task_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.ClaimJobResponse.task_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_task_name(), target);
  }

  // bytes payload = 3;
  if (!this->_internal_payload().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_payload(), target);
  }

  // int32 priority = 4;
  if (this->_internal_priority() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_priority(), target);
  }

  // int32 retry_count = 5;
  if (this->_internal_retry_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_retry_count(), target);
  }

  // int32 max_retries = 6;
  if (this->_internal_max_retries() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_max_retries(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jobqueue.ClaimJobResponse)
  return target;
}

size_t ClaimJobResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jobqueue.ClaimJobResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // string task_name = 2;
  if (!this->_internal_task_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_task_name());
  }

  // bytes payload = 3;
  if (!this->_internal_payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_payload());
  }

  // int32 priority = 4;
  if (this->_internal_priority() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_priority());
  }

  // int32 retry_count = 5;
  if (this->_internal_retry_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_retry_count());
  }

  // int32 max_retries = 6;
  if (this->_internal_max_retries() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_max_retries());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClaimJobResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClaimJobResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClaimJobResponse::GetClassData() const { return &_class_data_; }


void ClaimJobResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClaimJobResponse*>(&to_msg);
  auto& from = static_cast<const ClaimJobResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jobqueue.ClaimJobResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_task_name().empty()) {
    _this->_internal_set_task_name(from._internal_task_name());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if (from._internal_priority() != 0) {
    _this->_internal_set_priority(from._internal_priority());
  }
  if (from._internal_retry_count() != 0) {
    _this->_internal_set_retry_count(from._internal_retry_count());
  }
  if (from._internal_max_retries() != 0) {
    _this->_internal_set_max_retries(from._internal_max_retries());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClaimJobResponse::CopyFrom(const ClaimJobResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jobqueue.ClaimJobResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClaimJobResponse::IsInitialized() const {
  return true;
}

void ClaimJobResponse::InternalSwap(ClaimJobResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.task_name_, lhs_arena,
      &other->_impl_.task_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.payload_, lhs_arena,
      &other->_impl_.payload_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClaimJobResponse, _impl_.max_retries_)
      + sizeof(ClaimJobResponse::_impl_.max_retries_)
      - PROTOBUF_FIELD_OFFSET(ClaimJobResponse, _impl_.priority_)>(
          reinterpret_cast<char*>(&_impl_.priority_),
          reinterpret_cast<char*>(&other->_impl_.priority_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ClaimJobResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jobqueue_2eproto_getter, &descriptor_table_jobqueue_2eproto_once,
      file_level_metadata_jobqueue_2eproto[1]);
}

// ===================================================================

class CompleteJobRequest::_Internal {
 public:
};

CompleteJobRequest::CompleteJobRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jobqueue.CompleteJobRequest)
}
CompleteJobRequest::CompleteJobRequest(const CompleteJobRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CompleteJobRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.worker_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_worker_id().empty()) {
    _this->_impl_.worker_id_.Set(from._internal_worker_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:jobqueue.CompleteJobRequest)
}

inline void CompleteJobRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.worker_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CompleteJobRequest::~CompleteJobRequest() {
  // @@protoc_insertion_point(destructor:jobqueue.CompleteJobRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CompleteJobRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.job_id_.Destroy();
  _impl_.worker_id_.Destroy();
}

void CompleteJobRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CompleteJobRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:jobqueue.CompleteJobRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  _impl_.worker_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CompleteJobRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.CompleteJobRequest.job_id"));
        } else
          goto handle_unusual;
        continue;
      // string worker_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_worker_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.CompleteJobRequest.worker_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CompleteJobRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jobqueue.CompleteJobRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.CompleteJobRequest.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // string worker_id = 2;
  if (!this->_internal_worker_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_worker_id().data(), static_cast<int>(this->_internal_worker_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.CompleteJobRequest.worker_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_worker_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jobqueue.CompleteJobRequest)
  return target;
}

size_t CompleteJobRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jobqueue.CompleteJobRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // string worker_id = 2;
  if (!this->_internal_worker_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_worker_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CompleteJobRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CompleteJobRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CompleteJobRequest::GetClassData() const { return &_class_data_; }


void CompleteJobRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CompleteJobRequest*>(&to_msg);
  auto& from = static_cast<const CompleteJobRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jobqueue.CompleteJobRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_worker_id().empty()) {
    _this->_internal_set_worker_id(from._internal_worker_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CompleteJobRequest::CopyFrom(const CompleteJobRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jobqueue.CompleteJobRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompleteJobRequest::IsInitialized() const {
  return true;
}

void CompleteJobRequest::InternalSwap(CompleteJobRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.worker_id_, lhs_arena,
      &other->_impl_.worker_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CompleteJobRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jobqueue_2eproto_getter, &descriptor_table_jobqueue_2eproto_once,
      file_level_metadata_jobqueue_2eproto[2]);
}

// ===================================================================

class FailJobRequest::_Internal {
 public:
};

FailJobRequest::FailJobRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jobqueue.FailJobRequest)
}
FailJobRequest::FailJobRequest(const FailJobRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FailJobRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.worker_id_){}
    , decltype(_impl_.error_msg_){}
    , decltype(_impl_.permanent_){}
    , decltype(_impl_.retry_count_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_worker_id().empty()) {
    _this->_impl_.worker_id_.Set(from._internal_worker_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.error_msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_msg().empty()) {
    _this->_impl_.error_msg_.Set(from._internal_error_msg(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.permanent_, &from._impl_.permanent_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.retry_count_) -
    reinterpret_cast<char*>(&_impl_.permanent_)) + sizeof(_impl_.retry_count_));
  // @@protoc_insertion_point(copy_constructor:jobqueue.FailJobRequest)
}

inline void FailJobRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.worker_id_){}
    , decltype(_impl_.error_msg_){}
    , decltype(_impl_.permanent_){false}
    , decltype(_impl_.retry_count_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FailJobRequest::~FailJobRequest() {
  // @@protoc_insertion_point(destructor:jobqueue.FailJobRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FailJobRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.job_id_.Destroy();
  _impl_.worker_id_.Destroy();
  _impl_.error_msg_.Destroy();
}

void FailJobRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FailJobRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:jobqueue.FailJobRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  _impl_.worker_id_.ClearToEmpty();
  _impl_.error_msg_.ClearToEmpty();
  ::memset(&_impl_.permanent_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.retry_count_) -
      reinterpret_cast<char*>(&_impl_.permanent_)) + sizeof(_impl_.retry_count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FailJobRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.FailJobRequest.job_id"));
        } else
          goto handle_unusual;
        continue;
      // string worker_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_worker_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.FailJobRequest.worker_id"));
        } else
          goto handle_unusual;
        continue;
      // string error_msg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_error_msg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.FailJobRequest.error_msg"));
        } else
          goto handle_unusual;
        continue;
      // bool permanent = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.permanent_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 retry_count = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.retry_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FailJobRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jobqueue.FailJobRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.FailJobRequest.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // string worker_id = 2;
  if (!this->_internal_worker_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_worker_id().data(), static_cast<int>(this->_internal_worker_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.FailJobRequest.worker_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_worker_id(), target);
  }

  // string error_msg = 3;
  if (!this->_internal_error_msg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_msg().data(), static_cast<int>(this->_internal_error_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.FailJobRequest.error_msg");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_error_msg(), target);
  }

  // bool permanent = 4;
  if (this->_internal_permanent() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_permanent(), target);
  }

  // int32 retry_count = 5;
  if (this->_internal_retry_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_retry_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jobqueue.FailJobRequest)
  return target;
}

size_t FailJobRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jobqueue.FailJobRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // string worker_id = 2;
  if (!this->_internal_worker_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_worker_id());
  }

  // string error_msg = 3;
  if (!this->_internal_error_msg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_msg());
  }

  // bool permanent = 4;
  if (this->_internal_permanent() != 0) {
    total_size += 1 + 1;
  }

  // int32 retry_count = 5;
  if (this->_internal_retry_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_retry_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FailJobRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FailJobRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FailJobRequest::GetClassData() const { return &_class_data_; }


void FailJobRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FailJobRequest*>(&to_msg);
  auto& from = static_cast<const FailJobRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jobqueue.FailJobRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_worker_id().empty()) {
    _this->_internal_set_worker_id(from._internal_worker_id());
  }
  if (!from._internal_error_msg().empty()) {
    _this->_internal_set_error_msg(from._internal_error_msg());
  }
  if (from._internal_permanent() != 0) {
    _this->_internal_set_permanent(from._internal_permanent());
  }
  if (from._internal_retry_count() != 0) {
    _this->_internal_set_retry_count(from._internal_retry_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FailJobRequest::CopyFrom(const FailJobRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jobqueue.FailJobRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FailJobRequest::IsInitialized() const {
  return true;
}

void FailJobRequest::InternalSwap(FailJobRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.worker_id_, lhs_arena,
      &other->_impl_.worker_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_msg_, lhs_arena,
      &other->_impl_.error_msg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FailJobRequest, _impl_.retry_count_)
      + sizeof(FailJobRequest::_impl_.retry_count_)
      - PROTOBUF_FIELD_OFFSET(FailJobRequest, _impl_.permanent_)>(
          reinterpret_cast<char*>(&_impl_.permanent_),
          reinterpret_cast<char*>(&other->_impl_.permanent_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FailJobRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jobqueue_2eproto_getter, &descriptor_table_jobqueue_2eproto_once,
      file_level_metadata_jobqueue_2eproto[3]);
}

// ===================================================================

class JobAck::_Internal {
 public:
};

JobAck::JobAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jobqueue.JobAck)
}
JobAck::JobAck(const JobAck& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  JobAck* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:jobqueue.JobAck)
}

inline void JobAck::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

JobAck::~JobAck() {
  // @@protoc_insertion_point(destructor:jobqueue.JobAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void JobAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.job_id_.Destroy();
}

void JobAck::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void JobAck::Clear() {
// @@protoc_insertion_point(message_clear_start:jobqueue.JobAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JobAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "jobqueue.JobAck.job_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* JobAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jobqueue.JobAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jobqueue.JobAck.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jobqueue.JobAck)
  return target;
}

size_t JobAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jobqueue.JobAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JobAck::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    JobAck::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JobAck::GetClassData() const { return &_class_data_; }


void JobAck::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<JobAck*>(&to_msg);
  auto& from = static_cast<const JobAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jobqueue.JobAck)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JobAck::CopyFrom(const JobAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jobqueue.JobAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JobAck::IsInitialized() const {
  return true;
}

void JobAck::InternalSwap(JobAck* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata JobAck::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_jobqueue_2eproto_getter, &descriptor_table_jobqueue_2eproto_once,
      file_level_metadata_jobqueue_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace jobqueue
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::jobqueue::ClaimJobRequest*
Arena::CreateMaybeMessage< ::jobqueue::ClaimJobRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jobqueue::ClaimJobRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::jobqueue::ClaimJobResponse*
Arena::CreateMaybeMessage< ::jobqueue::ClaimJobResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jobqueue::ClaimJobResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::jobqueue::CompleteJobRequest*
Arena::CreateMaybeMessage< ::jobqueue::CompleteJobRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jobqueue::CompleteJobRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::jobqueue::FailJobRequest*
Arena::CreateMaybeMessage< ::jobqueue::FailJobRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jobqueue::FailJobRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::jobqueue::JobAck*
Arena::CreateMaybeMessage< ::jobqueue::JobAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jobqueue::JobAck >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
